### ISSUE TITLE
Packages to Automatically Install on Hosts/Thin Clients

### ISSUE THREAD

**Issue by adamkrellenstein** [towercomputers/toweros#100]
# Thin Client
* nmap

**Comment by ouziel-slama** [comment]
Do we want a command `tower install thinclient <app_name>` to install a package using the `router`  as tunnel ?

**Comment by adamkrellenstein** [comment]
ah what's the situation now??

**Comment by ouziel-slama** [comment]
now you must to connect the thin client to internet with the `router`..

**Comment by adamkrellenstein** [comment]
ah how? manually?

**Comment by ouziel-slama** [comment]
https://towercomputers.github.io/toweros/development/#set-up-development-environment ;-)

**Comment by adamkrellenstein** [comment]
ah yes! now that makes sense.

I think we should do the tunnel... Maybe add a confirmation in red: "Are you sure you want to install a package directly on the thin client? This is a *dangerous* operation and only rarely necessary. (y/N)"

**Comment by ouziel-slama** [comment]
see https://github.com/towercomputers/toweros/issues/114

**Comment by ouziel-slama** [comment]
`nmap`  is installed by default now. Keeping open if more apps are needed.

**Comment by adamkrellenstein** [comment]
Can you think of any other useful tools for debugging??

**Comment by ouziel-slama** [comment]
hum.. nope.. 
here all the installed packages for now: https://github.com/towercomputers/toweros/blob/master/scripts/toweros-thinclient/etc/apk/world

**Comment by adamkrellenstein** [comment]
okay let's just close this issue for now then! if you think of something useful, just add it :)

**Comment by adamkrellenstein** [comment]
and maybe it'd be useful to spend 5 minutes categorizing the packages in that list? dependencies, debugging, etc.?? (maybe that'd be useless I'm not sure)

**Comment by ouziel-slama** [comment]
yeah  agreed! will be cleaner!
