### ISSUE TITLE
Improve Secret Storage?

### ISSUE THREAD

**Issue by adamkrellenstein** [towercomputers/toweros#118]
![Screenshot 2023-11-05 at 9 43 41 PM](https://github.com/towercomputers/toweros/assets/6189829/10026a26-67fa-4785-8ede-5ab36e4d82e8)

Is there a better way to do this? Should we be setting the permissions on these files? etc.

**Comment by ouziel-slama** [comment]
for the first one we could just set the permission to 600 like ssh private key ? 
The two others are false positive I think.

**Comment by adamkrellenstein** [comment]
Sounds good!

**Comment by ouziel-slama** [comment]
done here https://github.com/towercomputers/toweros/commit/147b8a45767067f152fa8531c7a13469ae0b2dc5
