### ISSUE TITLE
Thin Client Disk Encryption

### ISSUE THREAD

**Issue by adamkrellenstein** [towercomputers/toweros#125]
Right now, it's optional to encrypt the thin client's root fs with a key stored in a separate boot volume.

There are a few other possibilities:
1. make it mandatory (like host root fs encryption)
2. make it a passphrase, since the thin client has a keyboard
3. make it either a passphrase or a separate boot volume (or neither)

**Comment by ouziel-slama** [comment]
I like the 3 but this adds a question or two during installation.

**Comment by adamkrellenstein** [comment]
So the argument for (1) is that the user is already carrying around a bunch of USB keys / SD cards to decrypt the root filesystems on the host... wouldn't the user also want a USB key for the thin client? seems weird to have a passphrase for the thin client and keys for the hosts...

**Comment by ouziel-slama** [comment]
yep I agree that number 1 is the one that matches the spirit of the project the most..

**Comment by adamkrellenstein** [comment]
okay yep, let's go with (1)

**Comment by ouziel-slama** [comment]
done!
