### ISSUE TITLE
Elegantly Handle Apparently Incomplete Provisioning of a Host

### ISSUE THREAD

**Issue by adamkrellenstein** [towercomputers/toweros#126]
Save the credentials + config at the beginning of the process? Helpful error message?

**Comment by ouziel-slama** [comment]
> Save the credentials + config at the beginning of the process?

this is done!

> Helpful error message?

when exactly ? on ctrl-c or after a timeout ?
not sure what kind of message to put here... a link to the "troubleshooting" page in the doc ?

**Comment by adamkrellenstein** [comment]
I'd say on either ctrl-c or a timeout, yeah a link to the troubleshooting page would be good. (And on the troubleshooting page, describe using a monitor and usb keyboard to debug.)

**Comment by ouziel-slama** [comment]
done here https://github.com/towercomputers/toweros/commit/423dd0e3de58b8dc91543659f20f617f2f29af9e
