### ISSUE TITLE
Troubleshooting Material for Docs

### ISSUE THREAD

**Issue by adamkrellenstein** [towercomputers/toweros#140]
This can go under `#Installation`:

![Screenshot 2023-11-15 at 8 52 45 AM](https://github.com/towercomputers/toweros/assets/6189829/7742dc2e-11e7-45f5-a386-cfd6d0228512)

**Comment by ouziel-slama** [comment]
"to avoid installation errors make sure you've never used your root drive as a boot drive."

**Comment by ouziel-slama** [comment]
done here: https://github.com/towercomputers/toweros/commit/25ae26bcfcaf1b3ce3fe3a34abc6d010df8532c8
