### ISSUE TITLE
Reorganize folder ~/.local/tower

### ISSUE THREAD

**Issue by ouziel-slama** [towercomputers/toweros#143]
~/.local/tower/config for the ssh config included in ~/.ssh/config

then one folder by hostname:

```
~/.local/tower/<hostname>/tower.env (configuration file)
~/.local/tower/<hostname>/id_ed25519 (ssh private key)
~/.local/tower/<hostname>/id_ed25519.pub (ssh public key)
~/.local/tower/<hostname>/crypto_keyfile.bin (luks key)
~/.local/tower/<hostname>/world (installed apks with `tower install`)
```

add in documentation

**Comment by adamkrellenstein** [comment]
Hm, I'm not sure I follow...

Should it be `~/.local/tower/hosts/<hostname>` for all of the host-specific stuff? Then we can store the system-wide stuff in `~/.local/tower/`?

**Comment by ouziel-slama** [comment]
hum.. why an additional subfolder ?  `~/.local/tower/<hostname>` for all of the host-specific stuff and `~/.local/tower/` for system-wide.. in fact there is only one system-wide file it's `~/.local/tower/config` for now. I can't see any other system-wild file we would need..

**Comment by adamkrellenstein** [comment]
no that works!

**Comment by ouziel-slama** [comment]
hum.. no! you right :-)) don't want to make `config` a reserved name :)

**Comment by ouziel-slama** [comment]
fixed!
