### ISSUE TITLE
Slow Network Transfer Speeds (?)

### ISSUE THREAD

**Issue by adamkrellenstein** [towercomputers/toweros#150]

**Comment by ouziel-slama** [comment]
<img width="599" alt="Capture d’écran 2023-11-20 à 11 56 39" src="https://github.com/towercomputers/toweros/assets/4574979/3c796a64-cf73-4c1e-ac9d-6a092f4eb13a">

I tested with iperf and I don't see any problem. This must come from the hardware (switch, cable, USB key, etc.)
