### ISSUE TITLE
Single Host Network Only: Distinguish Between Online and Offline Hosts in Router Firewall Rules

### ISSUE THREAD

**Issue by adamkrellenstein** [towercomputers/toweros#154]
With the appropriate firewall rules in the router segregating offline hosts from the Internet, there's no difference between online and offline hosts, right?

In other words, none of these rules would have to change: https://toweros.org/security/#security-model

**Comment by ouziel-slama** [comment]
Also firewall rules are not exactly the same on online and offline host:

- Offline hosts reject all outgoing traffic.
- Online hosts reject outgoing traffic directed to the thin client or to other hosts.

(see https://toweros.org/implementation/#firewall-rules and https://github.com/towercomputers/toweros/blob/master/tower-lib/toweros-installers/toweros-host/installer/configure-firewall.sh#L63-L78)

**Comment by adamkrellenstein** [comment]
hm, okay I was being silly when I thought of this.
