### ISSUE TITLE
Colored Window Borders

### ISSUE THREAD

**Issue by ouziel-slama** [towercomputers/toweros#161]
Use the same color as the shell prompt

**Comment by ouziel-slama** [comment]
A solution, to explore, compatible with all WM would be to embed the applications launched with `tower run` in a container application whose appearance we would control. See https://stackoverflow.com/questions/1009813/how-to-embed-some-application-window-in-my-application-using-any-python-gui-fram

**Comment by adamkrellenstein** [comment]
I think that works! As long as it doesn't require any big dependencies (like GTK)...

**Comment by adamkrellenstein** [comment]
We should have a flag to turn this off, per application run.

**Comment by ouziel-slama** [comment]
@adamkrellenstein, ok I did a lot of research and testing and it's meh! I tried three solutions:

1) use labwc/openbox features, but this is not possible. Themes do not support window rules, and rc.xml supports window rules but cannot modify colors (which are the responsibility of the theme..).
2) Run the application inside another application. For security reasons, quite obvious in fact, this is not possible without the cooperation of the on-board application.
3) Launch a second application, just a colored square, which would automatically be placed under the application you want to decorate. This is not possible with Wayland/Labwc which does not allow you to recover the properties of other applications (_NET_WM_DESKTOP not supported)

I think the cleanest solution would be to fork Labwc to slightly modify this functionality:
https://www.mankier.com/5/labwc-config#Configuration-Window_Rules
The idea would be to be able to add a rule like this:

```
<windowRule identifier="office:*" theme="tower-red" />
```

which would allow you to assign a specific theme for all applications on a given host.

The only problem is that Labwc is written in C and I have never used this language! not even afraid lol, but I don't know how long it can take!

**Comment by adamkrellenstein** [comment]
Okay gotcha. I think we can just delay this.

In the meantime, can we change the window title to say `browser — firefox` or something like that?

**Comment by ouziel-slama** [comment]
> In the meantime, can we change the window title to say browser — firefox or something like that?

nope sorry, it's exactly the same problem as for the color :-/
let just plan asap at least three of four days for a labwc fork.. I don't think we have a choice, it seems to me a critical functionality.

**Comment by adamkrellenstein** [comment]
Hm, I think we should just put it off then... I think it's not a critical feature pre–v1.0.0

**Comment by ouziel-slama** [comment]
ok I continue to think/look for a solution alongside the rest!

**Comment by ouziel-slama** [comment]
Done with `vnc` using a `gtk-vnc` custom vnc viewer.
