### ISSUE TITLE
Browser Security Something

### ISSUE THREAD

**Issue by adamkrellenstein** [towercomputers/toweros#170]
Is this a Midori problem, or an Alpine problem, or a TowerOS problem?

![image](https://github.com/towercomputers/toweros/assets/6189829/f6ed6603-c373-4551-84c3-d48e46cc329a)

![image](https://github.com/towercomputers/toweros/assets/6189829/f9a4f209-6b71-48d0-9765-62eb97bc58a7)![image](https://github.com/towercomputers/toweros/assets/6189829/a415118d-24cb-4f52-afe4-d9ee9a6482cc)

**Comment by ouziel-slama** [comment]
hum.. works well for me on a fresh online host.
@adamkrellenstein could you check the date of the host please ?

**Comment by adamkrellenstein** [comment]
Ah good idea—that explains it.
