### ISSUE TITLE
NX Configuration Parameters

### ISSUE THREAD

**Issue by adamkrellenstein** [towercomputers/toweros#171]
There's very high bandwidth usage on both the thin client and the host, and that makes software over NX too jumpy. This happens almost constantly even with static websites, and also when using Okular, even when just scrolling. (>5MiB/s). Seems like NX needs to be reconfigured at least. May ofc. need to switch to Moonlight. Maybe worse because of `lo` device?!
 
 Make NX settings configurable with CLI params to `tower run`.

**Comment by ouziel-slama** [comment]
done here: https://github.com/towercomputers/toweros/commit/acd21f89f57371cc1d0689a76ce56b6a8125dc52
added 3 flags: `--nx-link`, `--nx-stream` and `--nx-limit`.
See https://manpages.debian.org/testing/nxproxy/nxproxy.1.en.html#NX/NX_DISPLAY_OPTIONS
