### ISSUE TITLE
Cannot Run Curses on Host with SSH

### ISSUE THREAD

**Issue by adamkrellenstein** [towercomputers/toweros#188]
`pinentry-curses` and `cfdisk` e.g.

**Comment by adamkrellenstein** [comment]
![image](https://github.com/towercomputers/toweros/assets/6189829/e866481b-3824-4f3b-9151-b0bf8a424150)

**Comment by ouziel-slama** [comment]
@adamkrellenstein you need the `-t` flags: `ssh -t office sudo cfdisk` works for me.

**Comment by adamkrellenstein** [comment]
ach I thought I tried that...

**Comment by adamkrellenstein** [comment]
![image](https://github.com/towercomputers/toweros/assets/6189829/05e3e995-845f-484e-a2fb-a8a73dfa0514)

**Comment by ouziel-slama** [comment]
@adamkrellenstein `tower install storage foot` then retry `ssh -t storage sudo cfdisk`
