### ISSUE TITLE
Refactor `tower install` ?

### ISSUE THREAD

**Issue by ouziel-slama** [towercomputers/toweros#191]
Use `apk fetch` on online host, copy the packages on online host then `apk add *.apk`.
Make the codebase enough generic to easily add support for other package manager (always the same principle: download, copy and install).
It's simpler and more generic that the current system with a tunnel.

**Comment by ouziel-slama** [comment]
Actually, ultimately, I don't think it's a good idea.

- firstly because we must discourage the installation of applications by means other than APK, so there is no real need to have a generic system.
- with the current system we execute `apk` directly on the destination host transparently, so there is less chance of having dependency problems.
- I reread the code and what we do is clean :) clearly a little more complex than a download/copy/install but the end result is more elegant imho :)

@adamkrellenstein  if you're ok I'll close.

**Comment by adamkrellenstein** [comment]
Yep I'm fine with that! Seems like the only thing we're missing is the ease of debugging, but that's not even v helpful because most errors will be network-related.

**Comment by ouziel-slama** [comment]
also for debugging is better now.. the output of `tower install` is exactly the same as the output of `apk add` in online host..
