### ISSUE TITLE
VNC Improvements

### ISSUE THREAD

**Issue by ouziel-slama** [towercomputers/toweros#210]
- [ ] Detect child windows outside the main window and resize the vnc viewer so that they are visible.
- [ ] Find a reliable way to close application inside the vnc viewer (a force close button ?)
- [ ] Optimize for video

**Comment by ouziel-slama** [comment]
> Detect child windows outside the main window and resize the vnc viewer so that they are visible.

The only way I see to do this is to have a dameon on the host that monitors all open windows in an xvfb display and sends a message to the thinclient via an ssh tunnel when a new window is opened.. I think it's annoying to add a service on the hosts for this especially since normally it only takes a little cooperation from the user to solve the problem (by right clicking elsewhere or by enlarging the vnc viewer).

> Find a reliable way to close application inside the vnc viewer (a force close button ?)

The main problem is when a user clicks the close button and the main window does not have focus (for example when a menu is open). I tried everything (xdotool, wmctrl and Xlib) to send a 'ctrl-q' to all windows instead of just the one with focus but it doesn't work. Besides, I tried with Mousepad installed on the Thin Client, and when you click on close with a menu open it closes the menu, you have to click a second time to close the application. In short, as for the first point I think that in the vast majority of cases the problem is resolved with a little bit of cooperation from the user (here just by closing the menu which is quite instinctive in the end).
On the other hand, it would still be nice to have a way to force quit an application (by doing `ssh <host> killall <application_name>`). The ideal would be to have a "force quit" when you right-click on the application in the taskbar (like on macos)... I opened an issue here https://github.com/LBCrion/sfwbar/issues/132 because at the moment I don't see how to do it.

> Optimize for video

in fact the videos run pretty well on firefox+youtube, but it's Firefox that lags while the video is playing.. I tried all the settings that seemed interesting to me and it already runs much better.. I added a flag `--vnc-speeds` (see -speeds in the x11vnc man) and tried lots of settings but none work better.. I think that here we especially reach the processor limit (when we make a `top` on the host when a video plays) and I'm not sure we can do better at the software level..

@adamkrellenstein

**Comment by adamkrellenstein** [comment]
> > Detect child windows outside the main window and resize the vnc viewer so that they are visible.
> 
> The only way I see to do this is to have a dameon on the host that monitors all open windows in an xvfb display and sends a message to the thinclient via an ssh tunnel when a new window is opened.. I think it's annoying to add a service on the hosts for this especially since normally it only takes a little cooperation from the user to solve the problem (by right clicking elsewhere or by enlarging the vnc viewer).

Agreed!


> > Find a reliable way to close application inside the vnc viewer (a force close button ?)
> 
> The main problem is when a user clicks the close button and the main window does not have focus (for example when a menu is open). I tried everything (xdotool, wmctrl and Xlib) to send a 'ctrl-q' to all windows instead of just the one with focus but it doesn't work. Besides, I tried with Mousepad installed on the Thin Client, and when you click on close with a menu open it closes the menu, you have to click a second time to close the application. In short, as for the first point I think that in the vast majority of cases the problem is resolved with a little bit of cooperation from the user (here just by closing the menu which is quite instinctive in the end). On the other hand, it would still be nice to have a way to force quit an application (by doing `ssh <host> killall <application_name>`). The ideal would be to have a "force quit" when you right-click on the application in the taskbar (like on macos)... I opened an issue here [LBCrion/sfwbar#132](https://github.com/LBCrion/sfwbar/issues/132) because at the moment I don't see how to do it.

Okay sounds fine for now. Maybe let's open a separate issue for this and address it at some point in the future.


> > Optimize for video
> 
> in fact the videos run pretty well on firefox+youtube, but it's Firefox that lags while the video is playing.. I tried all the settings that seemed interesting to me and it already runs much better.. I added a flag `--vnc-speeds` (see -speeds in the x11vnc man) and tried lots of settings but none work better.. I think that here we especially reach the processor limit (when we make a `top` on the host when a video plays) and I'm not sure we can do better at the software level..

Gotcha! What speeds work best for you? What's the default? I wonder if there's a way to reduce the CPU load of firefox itself...

Have you tried using `nice` with different Firefox subprocesses? Maybe that would be interesting as a diagnostic exercise.

Is this an issue with the RPi 5 as well?

**Comment by ouziel-slama** [comment]
> Okay sounds fine for now. Maybe let's open a separate issue for this and address it at some point in the future.

The `sfwbar` developer is super reactive and already added a feature to make what we need! opened an issue for this here: https://github.com/towercomputers/toweros/issues/231

> Okay sounds fine for now. Maybe let's open a separate issue for this and address it at some point in the future.

when I don't use the option and let x11vnc to decide..

> I wonder if there's a way to reduce the CPU load of firefox itself...

yeah! this application definitely needs special treatment.. there are already hardcoded `x11vnc` options only for Firefox.. I opened an issue here: https://github.com/towercomputers/toweros/issues/230

> Is this an issue with the RPi 5 as well?

nope!  works well on RPi 5 !
