### ISSUE TITLE
Host Backup Procedure / Tooling

### ISSUE THREAD

**Issue by adamkrellenstein** [towercomputers/toweros#23]
TLDR; restic script using a SSH/GPG key on the Thin Client.

One restic repository per host, all saved regularly to a USB key plugged into one of the offline hosts.

**Comment by ouziel-slama** [comment]
@adamkrellenstein do we always want a backup system or do we let the user choose how to do it?

**Comment by adamkrellenstein** [comment]
I think we should *start* with a simple guide in the docs as to how to do a simple backup system using standard tools.

**Comment by ouziel-slama** [comment]
by "standard tools" you mean backup tools like restic or tools like `tar` and `scp` ?

**Comment by adamkrellenstein** [comment]
hm yeah or `borg` or `restic`??

**Comment by ouziel-slama** [comment]
Restic seems to me the simpler to use with ssh, I tested that and works well:

1. Install restic

        [thinclient]$ tower install storage restic
        [thinclient]$ tower install office restic
        [thinclient]$ tower install thinclient restic

1. Initialize restic repo in each host
        
        [thinclient]$ ssh -t storage restic -r /home/tower/backup init
        [thinclient]$ ssh -t office restic -r /home/tower/backup init

1. Backup `office`

        [thinclient]$ ssh -t office restic -r /home/tower/backup backup /home/tower/mydata

1. Copy `office` snapshot into `storage` repo

        [thinclient]$ restic -r sftp:storage:/home/tower/backup copy --from-repo sftp:office:/home/tower/backup latest

1. Restore backup into `office`

        [thinclient]$ restic -r sftp:office:/home/tower/backup copy --from-repo sftp:storage:/home/tower/backup latest --host office
        [thinclient]$ ssh -t office restic -r /home/tower/backup restore latest --target /

**Comment by ouziel-slama** [comment]
see https://github.com/towercomputers/toweros/commit/a88a7a13236ce0a368e2e3641379d7c6a681e644

**Comment by adamkrellenstein** [comment]
beautiful! 🤩

**Comment by ouziel-slama** [comment]
done!
