### ISSUE TITLE
Paste Isn't Working?

### ISSUE THREAD

**Issue by adamkrellenstein** [towercomputers/toweros#57]
I can copy/cut something from one window, and Parcelite sees it, but then I don't know how to paste that value into another application window.

**Comment by ouziel-slama** [comment]
fixed here https://github.com/towercomputers/toweros/commit/a12323691df5930f04a89aba1ae20a02357fbb55
finally I used the workaround above with `copyq` which offers a system of hooks to execute a script when a copy is performed.. works well.
