### ISSUE TITLE
Tor Gateway in Router

### ISSUE THREAD

**Issue by adamkrellenstein** [towercomputers/toweros#62]
TOR

**Comment by ouziel-slama** [comment]
![tor1](https://github.com/towercomputers/toweros/assets/4574979/e8805312-e0d5-4776-b2aa-7c3b44e81256)
![tor2](https://github.com/towercomputers/toweros/assets/4574979/f5c19a58-2a71-4040-9dc1-2dfcf10fae6f)

ok well I gave up for a transparent tor proxy, it's too complex and not sure that it would be interesting to systematically pass all requests through tor (and above all I can't make it work :)), on the other hand tor is now installed on the router and from any online host it is possible to use it by configuring the application to use the tor proxy...

@adamkrellenstein is it ok for you ?

**Comment by adamkrellenstein** [comment]
Ah yep! Can we document this on the `Security` page, though?

**Comment by ouziel-slama** [comment]
yeah sure!

**Comment by ouziel-slama** [comment]
see https://github.com/towercomputers/toweros/commit/970bf358493b2b737e33ac5a807118a8f97457ee
