### ISSUE TITLE
Improvements to Documentation from QA

### ISSUE THREAD

**Issue by adamkrellenstein** [towercomputers/toweros#97]
# Document Hardware Requirements
* We should keep *all* discussion of hardware separate from discussing the software. We need a dedicated section in the documentation for it.
* SD cards for hosts (boot fs); recommended models
* USB drives for hosts (root fs); recommended models
* At least one Raspberry Pi (single online host)
* Thin Client
* Two Ethernet ports on Thin Client (or adapters); recommend models (https://www.olimex.com/Products/USB-Modules/USB-GIGABIT/open-source-hardware for fully open one)
* SD Card Reader for Thin Client (built-in, or adapter)
* Home WiFi router (the `router` needs to connect to this)... or de we also support ethernet?
* Suggested for debugging
    * Monitor
    * micro HDMI<->monitor cable adapter
    * USB keyboard
    * USB mouse
* One or two unmanaged switches (two if you want to support offline hosts)
* Support two configuration: Raspberry PI and CM4
* Recommended CM4 Configuration
  * DeskPi Super6C
  * Case
  * CM4 "Lite" version only; M.2 SSDs for storage (root volume)
  * Router CM4 doesn't need much RAM; doesn't need much storage; does need WiFi
  * Host CM4: RAM based on usage pattern; storage based on usage pattern; recommended no WiFi
  * the primary USB ports on the board are connected to one CM4 (module #1); this can be used for system backups e.g.

# Other Documentation Improvements
* you need a minimum of one online host, to allow for package management
* you can't put an offline host on the online network; if you only want one switch/DeskPi, then just call every host "online" (to reduce cost and physical size)
* the install instructions don't mention the removal of the SD card before insertion into the host/router
* clarify which machine all commands are run on (in the CLI prompt, say)
* make it clear that `build-tower-image` is a dev command
* there's no need for "--online-host" with `tower install`
* recommend the user run `startx` as soon as they get the thin client installed. makes host installation much easier to debug.
* when waiting for a host to come up during the provision command, let the user know that debugging requires hooking a monitor up to the host in question; also state that it can take ~10 minutes, depending mostly on the speed of the root fs
* "Please ensure the sd-card is *NOT* connected [...]" -> "Please ensure the sd-card is *NOT* connected to the Thin Client. [...]"

**Comment by adamkrellenstein** [comment]
I think these are the only bullets left?

- make it clear that `build-tower-image` is a dev command
- let the user know that debugging requires hooking a monitor up to the host in question; also state that it can take ~10 minutes, depending mostly on the speed of the root fs

**Comment by adamkrellenstein** [comment]
I think this is all done?

**Comment by ouziel-slama** [comment]
taking care now of:
 "when waiting for a host to come up during the provision command, let the user know that debugging requires hooking a monitor up to the host in question; also state that it can take ~10 minutes, depending mostly on the speed of the root fs". 
and after that all done!

**Comment by ouziel-slama** [comment]
done here https://github.com/towercomputers/toweros/commit/4ffbb5e75484c425464c58ad817540b2bf3bda30
